### ISSUE TITLE
About the size of query feature patches.

### ISSUE THREAD

**Issue by unpairdenosie** [sczhou/IGNN#1]
![搜狗截图20201013121121](https://user-images.githubusercontent.com/64568626/95814557-3f440f80-0d4d-11eb-916c-131f80d04a10.png)

Can you tell me the value of the _l_ x _l_ ? Thank you!

**Comment by sczhou** [comment]
Hi, 
Here we set patch size 3x3 for matching, which is better than the larger ones.

**Comment by unpairdenosie** [comment]
> Hi,
> Here we set patch size 3x3 for matching, which is better than the larger ones.

Excuse me, I'm a little confused. If the query patch is 3X3 and the LR images are 60X60, does it means that we need do 20X20=400 graph convolution for training a single LR  image?

**Comment by sczhou** [comment]
Hi, Actually, we set stride = 2 when extracting the 3*3 patches from an image. Thus, there are one-pixel overlaps between the two adjacent image patches. It will generate around 30*30 patches for your example.

**Comment by sczhou** [comment]
> Excuse me, I'm a little confused. If the query patch is 3X3 and the LR images are 60X60, does it means that we need do 20X20=400 graph convolution for training a single LR image?

Hi, Actually, we set stride = 2 when extracting the 3x3 patches from an image. Thus, there are one-pixel overlaps between the two adjacent image patches. It will generate around 30x30 patches for your example.
