### ISSUE TITLE
The PSNR is lower than its in the paper

### ISSUE THREAD

**Issue by jamekuma** [sczhou/IGNN#17]
Hello, I train the IGNN model as the config in README. But when the training is convergence, I can't get the PSNR as high as its in the paper:
|      | Set5 | Set14 | B100 | Urban100 | Manga109 |
| ---- | ---- | ----- | ---- | -------- | -------- |
|IGNN(Paper)|**38.24/0.9613**|**34.07/0.9217**|**32.41/0.9025**|**33.23/0.9383**|**39.35/0.9786**|
| IGNN(my test) | 38.15/0.9610 | 33.85/0.9199 | 32.30/0.9012 | 32.70/0.9337 | 38.94/0.9776 |

Are there any other tricks in training? thank you!

**Comment by sczhou** [comment]
Hi Jianyu,

Thank you for reaching out to me. Actually, we used the warm-up before
training. If you want to get the results in the paper, you could simply
change the LR scheduler with a warm restart, e.g.,
CosineAnnealingWarmRestarts(), and enlarge the epoch number. I think this
could boost the performance a lot.

Moreover, if you are interested in across-scale attention for SR, you could
also refer to another more efficient implementation proposed in a
concurrent work, *Image Super-Resolution with Cross-Scale Non-Local
Attention and Exhaustive Self-Exemplars Mining. *The main idea in this
paper is similar to ours but more efficient I think. Could check their code
and paper for more details.

Hope the above information could help you.

Best,
Shangchen

**Comment by sczhou** [comment]
Thank you for reaching out to me. Actually, we used the warm-up before training. If you want to get the results in the paper, you could simply change the LR scheduler with a warm restart, e.g., CosineAnnealingWarmRestarts(), and enlarge the epoch number. I think this could boost the performance a lot.

Moreover, if you are interested in across-scale attention for SR, you could also refer to another more efficient implementation proposed in a concurrent work, "Image Super-Resolution with Cross-Scale Non-Local Attention and Exhaustive Self-Exemplars Mining". The main idea in this paper is similar to ours but with more efficient implementation I think. Could check their [code](https://github.com/SHI-Labs/Cross-Scale-Non-Local-Attention) and paper for more details.

**Comment by jamekuma** [comment]
Thanks for your reply. Furthermore, are there any recommended CosineAnnealingWarmRestarts parameters such as T_0, T_mult?

**Comment by HolmesShuan** [comment]
> Actually, we used the warm-up before training. If you want to get the results in the paper, you could simply change the LR scheduler with a warm restart, e.g., CosineAnnealingWarmRestarts(), and enlarge the epoch number. I think this could boost the performance a lot.

@sczhou Hi, I have a similar concern about **warmup training**, as mentioned in @jamekuma's comments. Is this a common setting in deep learning-based SR methods? How to set `T_0` and `T_mult`?

Thanks in advance!
