### ISSUE TITLE
About the supplementary material

### ISSUE THREAD

**Issue by qiqiing** [sczhou/IGNN#2]
![image](https://user-images.githubusercontent.com/74251594/99205192-b52b1300-27f2-11eb-9071-1339ff1f7024.png)

Hello, in your paper, you mentioned: More detailed structures are provided in the supplementary material.Could you tell me how to find these supplementary materials?

**Comment by sczhou** [comment]
> Hello, in your paper, you mentioned: More detailed structures are provided in the supplementary material.Could you tell me how to find these supplementary materials?

Hi, you can find the supply. file from [here](https://proceedings.neurips.cc/paper/2020/file/23ad3e314e2a2b43b4c720507cec0723-Supplemental.pdf).
